// src/hooks/useAudioEngine.ts
import { useRef, useCallback, useEffect } from 'react';
import { useApp } from '../context/AppContext';

// FFT size for 36 bands — 2048 gives us 1024 frequency bins
const FFT_SIZE = 2048;
const BAND_COUNT = 36;

interface AudioEngineRefs {
  context: AudioContext | null;
    analyser: AnalyserNode | null;
      source: AudioBufferSourceNode | null;
        gainNode: GainNode | null;
          frequencyData: Uint8Array | null;
            startTime: number;
              pauseTime: number;
              }

              export function useAudioEngine() {
                const { audio, setAudioBuffer, setPlaying, updateCurrentTime } = useApp();
                  
                    const refs = useRef<AudioEngineRefs>({
                        context: null,
                            analyser: null,
                                source: null,
                                    gainNode: null,
                                        frequencyData: null,
                                            startTime: 0,
                                                pauseTime: 0,
                                                  });

                                                    // Initialize AudioContext on first interaction
                                                      const initContext = useCallback(() => {
                                                          if (!refs.current.context) {
                                                                const ctx = new (window.AudioContext || (window as any).webkitAudioContext)();
                                                                      const analyser = ctx.createAnalyser();
                                                                            const gainNode = ctx.createGain();
                                                                                  
                                                                                        analyser.fftSize = FFT_SIZE;
                                                                                              analyser.smoothingTimeConstant = 0.8;
                                                                                                    
                                                                                                          gainNode.connect(analyser);
                                                                                                                analyser.connect(ctx.destination);
                                                                                                                      
                                                                                                                            refs.current.context = ctx;
                                                                                                                                  refs.current.analyser = analyser;
                                                                                                                                        refs.current.gainNode = gainNode;
                                                                                                                                              refs.current.frequencyData = new Uint8Array(analyser.frequencyBinCount);
                                                                                                                                                  }
                                                                                                                                                      return refs.current.context;
                                                                                                                                                        }, []);

                                                                                                                                                          // Decode uploaded file to AudioBuffer
                                                                                                                                                            const decodeFile = useCallback(async (file: File) => {
                                                                                                                                                                const ctx = initContext();
                                                                                                                                                                    const arrayBuffer = await file.arrayBuffer();
                                                                                                                                                                        const audioBuffer = await ctx.decodeAudioData(arrayBuffer);
                                                                                                                                                                            setAudioBuffer(audioBuffer);
                                                                                                                                                                                return audioBuffer;
                                                                                                                                                                                  }, [initContext, setAudioBuffer]);

                                                                                                                                                                                    // Play the audio
                                                                                                                                                                                      const play = useCallback((buffer?: AudioBuffer) => {
                                                                                                                                                                                          const ctx = refs.current.context;
                                                                                                                                                                                              const gainNode = refs.current.gainNode;
                                                                                                                                                                                                  const targetBuffer = buffer || audio.audioBuffer;
                                                                                                                                                                                                      
                                                                                                                                                                                                          if (!ctx || !gainNode || !targetBuffer) return;

                                                                                                                                                                                                              // Resume context if suspended (autoplay policy)
                                                                                                                                                                                                                  if (ctx.state === 'suspended') {
                                                                                                                                                                                                                        ctx.resume();
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                // Stop existing source if any
                                                                                                                                                                                                                                    if (refs.current.source) {
                                                                                                                                                                                                                                          refs.current.source.stop();
                                                                                                                                                                                                                                                refs.current.source.disconnect();
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                        const source = ctx.createBufferSource();
                                                                                                                                                                                                                                                            source.buffer = targetBuffer;
                                                                                                                                                                                                                                                                source.connect(gainNode);
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                        const offset = refs.current.pauseTime;
                                                                                                                                                                                                                                                                            source.start(0, offset);
                                                                                                                                                                                                                                                                                refs.current.source = source;
                                                                                                                                                                                                                                                                                    refs.current.startTime = ctx.currentTime - offset;
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            setPlaying(true);

                                                                                                                                                                                                                                                                                                source.onended = () => {
                                                                                                                                                                                                                                                                                                      setPlaying(false);
                                                                                                                                                                                                                                                                                                            refs.current.pauseTime = 0;
                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                  }, [audio.audioBuffer, setPlaying]);

                                                                                                                                                                                                                                                                                                                    // Pause
                                                                                                                                                                                                                                                                                                                      const pause = useCallback(() => {
                                                                                                                                                                                                                                                                                                                          const ctx = refs.current.context;
                                                                                                                                                                                                                                                                                                                              if (refs.current.source && ctx) {
                                                                                                                                                                                                                                                                                                                                    refs.current.pauseTime = ctx.currentTime - refs.current.startTime;
                                                                                                                                                                                                                                                                                                                                          refs.current.source.stop();
                                                                                                                                                                                                                                                                                                                                                refs.current.source.disconnect();
                                                                                                                                                                                                                                                                                                                                                      refs.current.source = null;
                                                                                                                                                                                                                                                                                                                                                            setPlaying(false);
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                  }, [setPlaying]);

                                                                                                                                                                                                                                                                                                                                                                    // Get current 36-band frequency data (optimized for 60fps)
                                                                                                                                                                                                                                                                                                                                                                      const getFrequencyBands = useCallback((): number[] => {
                                                                                                                                                                                                                                                                                                                                                                          const analyser = refs.current.analyser;
                                                                                                                                                                                                                                                                                                                                                                              const frequencyData = refs.current.frequencyData;
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                      if (!analyser || !frequencyData) {
                                                                                                                                                                                                                                                                                                                                                                                            return new Array(BAND_COUNT).fill(0);
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                    analyser.getByteFrequencyData(frequencyData);
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            // Map 1024 bins to 36 bands (logarithmic distribution)
                                                                                                                                                                                                                                                                                                                                                                                                                const bands: number[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                    const binCount = frequencyData.length;
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                            for (let i = 0; i < BAND_COUNT; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                  // Logarithmic mapping for perceptual accuracy
                                                                                                                                                                                                                                                                                                                                                                                                                                        const lowFreq = Math.pow(i / BAND_COUNT, 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                              const highFreq = Math.pow((i + 1) / BAND_COUNT, 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const lowBin = Math.floor(lowFreq * binCount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const highBin = Math.min(Math.floor(highFreq * binCount), binCount - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let sum = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  let count = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for (let j = lowBin; j <= highBin; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sum += frequencyData[j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Normalize to 0-1 range
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      bands.push(count > 0 ? (sum / count) / 255 : 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return bands;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Get current playback time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const getCurrentTime = useCallback((): number => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const ctx = refs.current.context;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!ctx || !audio.isPlaying) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return refs.current.pauseTime;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return ctx.currentTime - refs.current.startTime;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, [audio.isPlaying]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Cleanup on unmount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (refs.current.source) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      refs.current.source.stop();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              refs.current.source.disconnect();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (refs.current.context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  refs.current.context.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    decodeFile,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        play,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pause,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                getFrequencyBands,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    getCurrentTime,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        initContext,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            analyser: refs.current.analyser,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }