// src/components/SoundPrintCanvas.tsx
import { useRef, useEffect, useCallback } from 'react';
import { BAND_COLORS, getBandRGB } from '../config/bandColors';

interface SoundPrintCanvasProps {
  getFrequencyBands: () => number[];
    isPlaying: boolean;
      countdown: number;
        onCapture: (dataUrl: string) => void;
        }

        const BAND_COUNT = 36;

        export function SoundPrintCanvas({ 
          getFrequencyBands, 
            isPlaying, 
              countdown,
                onCapture 
                }: SoundPrintCanvasProps) {
                  const canvasRef = useRef<HTMLCanvasElement>(null);
                    const trailCanvasRef = useRef<HTMLCanvasElement>(null);
                      const rafRef = useRef<number>(0);
                        const historyRef = useRef<number[][]>([]);
                          
                            // Performance: Pre-calculate band angles
                              const bandAnglesRef = useRef<{ start: number; end: number }[]>(
                                  Array.from({ length: BAND_COUNT }, (_, i) => ({
                                        start: (i / BAND_COUNT) * Math.PI * 2 - Math.PI / 2,
                                              end: ((i + 1) / BAND_COUNT) * Math.PI * 2 - Math.PI / 2,
                                                  }))
                                                    );

                                                      // Field diffusion intensity based on countdown
                                                        const getBlurIntensity = useCallback(() => {
                                                            if (countdown > 6) return 0;
                                                                // Exponential ramp in final 6 seconds
                                                                    return Math.pow((6 - countdown) / 6, 2) * 20;
                                                                      }, [countdown]);

                                                                        // Core render loop
                                                                          const render = useCallback(() => {
                                                                              const canvas = canvasRef.current;
                                                                                  const trailCanvas = trailCanvasRef.current;
                                                                                      if (!canvas || !trailCanvas) return;

                                                                                          const ctx = canvas.getContext('2d', { alpha: false });
                                                                                              const trailCtx = trailCanvas.getContext('2d', { alpha: true });
                                                                                                  if (!ctx || !trailCtx) return;

                                                                                                      const { width, height } = canvas;
                                                                                                          const centerX = width / 2;
                                                                                                              const centerY = height / 2;
                                                                                                                  const maxRadius = Math.min(width, height) * 0.42;
                                                                                                                      const minRadius = maxRadius * 0.15;

                                                                                                                          // Get current frequency data
                                                                                                                              const bands = getFrequencyBands();
                                                                                                                                  
                                                                                                                                      // Store in history for trail effect
                                                                                                                                          historyRef.current.push([...bands]);
                                                                                                                                              if (historyRef.current.length > 60) {
                                                                                                                                                    historyRef.current.shift();
                                                                                                                                                        }

                                                                                                                                                            // Clear main canvas
                                                                                                                                                                ctx.fillStyle = '#0a0a0a';
                                                                                                                                                                    ctx.fillRect(0, 0, width, height);

                                                                                                                                                                        // Fade trail canvas
                                                                                                                                                                            trailCtx.fillStyle = 'rgba(10, 10, 10, 0.03)';
                                                                                                                                                                                trailCtx.fillRect(0, 0, width, height);

                                                                                                                                                                                    // Draw historical trails (ghosting effect)
                                                                                                                                                                                        const historyLen = historyRef.current.length;
                                                                                                                                                                                            for (let h = 0; h < historyLen; h++) {
                                                                                                                                                                                                  const historicBands = historyRef.current[h];
                                                                                                                                                                                                        const age = (historyLen - h) / historyLen;
                                                                                                                                                                                                              const trailAlpha = age * 0.15;

                                                                                                                                                                                                                    for (let i = 0; i < BAND_COUNT; i++) {
                                                                                                                                                                                                                            const value = historicBands[i];
                                                                                                                                                                                                                                    if (value < 0.05) continue;

                                                                                                                                                                                                                                            const [r, g, b] = getBandRGB(i);
                                                                                                                                                                                                                                                    const radius = minRadius + (maxRadius - minRadius) * value * age;
                                                                                                                                                                                                                                                            const { start, end } = bandAnglesRef.current[i];

                                                                                                                                                                                                                                                                    trailCtx.beginPath();
                                                                                                                                                                                                                                                                            trailCtx.moveTo(centerX, centerY);
                                                                                                                                                                                                                                                                                    trailCtx.arc(centerX, centerY, radius, start, end);
                                                                                                                                                                                                                                                                                            trailCtx.closePath();
                                                                                                                                                                                                                                                                                                    trailCtx.fillStyle = `rgba(${r}, ${g}, ${b}, ${trailAlpha})`;
                                                                                                                                                                                                                                                                                                            trailCtx.fill();
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                          // Draw current frame bands (main visualization)
                                                                                                                                                                                                                                                                                                                              for (let i = 0; i < BAND_COUNT; i++) {
                                                                                                                                                                                                                                                                                                                                    const value = bands[i];
                                                                                                                                                                                                                                                                                                                                          const [r, g, b] = getBandRGB(i);
                                                                                                                                                                                                                                                                                                                                                const radius = minRadius + (maxRadius - minRadius) * value;
                                                                                                                                                                                                                                                                                                                                                      const { start, end } = bandAnglesRef.current[i];

                                                                                                                                                                                                                                                                                                                                                            // Glow layer
                                                                                                                                                                                                                                                                                                                                                                  const gradient = ctx.createRadialGradient(
                                                                                                                                                                                                                                                                                                                                                                          centerX, centerY, minRadius,
                                                                                                                                                                                                                                                                                                                                                                                  centerX, centerY, radius * 1.2
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                              gradient.addColorStop(0, `rgba(${r}, ${g}, ${b}, 0)`);
                                                                                                                                                                                                                                                                                                                                                                                                    gradient.addColorStop(0.7, `rgba(${r}, ${g}, ${b}, ${value * 0.6})`);
                                                                                                                                                                                                                                                                                                                                                                                                          gradient.addColorStop(1, `rgba(${r}, ${g}, ${b}, 0)`);

                                                                                                                                                                                                                                                                                                                                                                                                                ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.moveTo(centerX, centerY);
                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.arc(centerX, centerY, radius * 1.2, start, end);
                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.closePath();
                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.fillStyle = gradient;
                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.fill();

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Core band
                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.moveTo(centerX, centerY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.arc(centerX, centerY, radius, start, end);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.closePath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.fillStyle = `rgba(${r}, ${g}, ${b}, ${0.4 + value * 0.6})`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.fill();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Edge highlight
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.arc(centerX, centerY, radius, start, end);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.strokeStyle = `rgba(${r}, ${g}, ${b}, ${value})`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.lineWidth = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.stroke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Center void
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const voidGradient = ctx.createRadialGradient(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              centerX, centerY, 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    centerX, centerY, minRadius
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            voidGradient.addColorStop(0, '#0a0a0a');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                voidGradient.addColorStop(0.8, '#0a0a0a');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    voidGradient.addColorStop(1, 'rgba(10, 10, 10, 0.8)');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.arc(centerX, centerY, minRadius, 0, Math.PI * 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ctx.fillStyle = voidGradient;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.fill();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Composite trail layer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.drawImage(trailCanvas, 0, 0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Continue animation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isPlaying) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rafRef.current = requestAnimationFrame(render);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, [getFrequencyBands, isPlaying]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Capture final state
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const captureCanvas = useCallback(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const canvas = canvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!canvas) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const dataUrl = canvas.toDataURL('image/png', 1.0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onCapture(dataUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, [onCapture]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Trigger capture at countdown zero
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (countdown === 0 && isPlaying) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Small delay to ensure final frame renders
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setTimeout(captureCanvas, 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, [countdown, isPlaying, captureCanvas]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Start/stop render loop
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (isPlaying) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rafRef.current = requestAnimationFrame(render);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (rafRef.current) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cancelAnimationFrame(rafRef.current);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, [isPlaying, render]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Resize handler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const handleResize = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const canvas = canvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const trailCanvas = trailCanvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!canvas || !trailCanvas) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const size = Math.min(window.innerWidth, window.innerHeight) * 0.85;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              canvas.width = size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    canvas.height = size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          trailCanvas.width = size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                trailCanvas.height = size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        handleResize();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.addEventListener('resize', handleResize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return () => window.removeEventListener('resize', handleResize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const blurIntensity = getBlurIntensity();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="sound-print-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ref={trailCanvasRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="sound-print-trail"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ display: 'none' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ref={canvasRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="sound-print-canvas"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      filter: blurIntensity > 0 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? `blur(${blurIntensity}px)` 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transition: 'filter 0.5s ease-out',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }